Feature/arrays
tkalmykova/study pull request #1
Opened 2020-04-14 04:25 UTC by tkalmykova

2020-04-15 07:14 UTC, aelaa commented on test/exercise/arrays/solution.rb
> +          new_element
В Ruby (и еще в некоторых языках) всегда возвращается последнее вычисленное значение. Необязательно записывать его в переменную и потом отдельно указывать.
```
array.map do |element|
    element > 0 ? max_element : element
end
```

2020-04-15 07:19 UTC, tkalmykova commented on test/exercise/arrays/solution.rb
> +          new_element
спасибо! привычка из js возвращать результат:) это нужно исправить в коде?

2020-04-15 07:52 UTC, aelaa commented on test/exercise/arrays/solution.rb
> +          new_element
Да, во всех местах можно (у тебя в следующем задании так же :))

2020-04-15 11:28 UTC, tkalmykova commented on test/exercise/arrays/solution.rb
> +          new_element
@aelaa поправила, посмотри, пожалуйста

2020-04-15 11:38 UTC, artempartos requested changes

2020-04-15 11:38 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        max_element = array.max
надо реализовать свой метод max

2020-04-15 11:38 UTC, artempartos commented on test/exercise/arrays/solution.rb
> +        while start_index <= end_index
давай попробуем реализовать без while , а рекурсивно, как вы вызывая метод search уточняя параметры

2020-04-15 11:39 UTC, aelaa commented on test/exercise/arrays/solution.rb
> +        return array[0] == query ? 0 : -1 if array.length == 1
Запись плохая.
В разных языках (и даже разные операторы в одном языке) ассоциативность операций может быть разной.
Если расставлять скобки в этом выражении, есть много способов его вычислить:
`return (((array[0] == query) ? 0 : -1) if array.length == 1)`
`return (array[0] == (query ? 0 : (-1 if array.length == 1)))`
`return (array[0] == query) ? 0 : (-1 if array.length == 1)`
И результат будет разным. 
Лучше вообще не злоупотреблять тернарным оператором. Иногда лучше написать в несколько строчек. Это тоже guard expression, если в нём есть return, и else там будет не нужен

2020-04-16 08:16 UTC, Andrew8xx8 requested changes

2020-04-16 08:16 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        binary_search = lambda do |start_index, end_index|
C лямбдой не очень понятное решение получается, можешь переписать используя просто вызов функции

2020-04-16 09:16 UTC, tkalmykova commented on test/exercise/arrays/solution.rb
> +        binary_search = lambda do |start_index, end_index|
@Andrew8xx8, нужно переписать вызывая именно функцию search или нужно вынести лямбду в отдельный метод?

2020-04-16 13:15 UTC, Andrew8xx8 commented on test/exercise/arrays/solution.rb
> +        binary_search = lambda do |start_index, end_index|
Можно вынести просто в отдельный метод

2020-04-17 09:45 UTC, Andrew8xx8 approved these changes

2020-04-17 10:45 UTC, merged