Feature/fp2
tkalmykova/study pull request #3
Opened 2020-04-16 12:46 UTC by tkalmykova

2020-04-16 13:14 UTC, Andrew8xx8 requested changes

2020-04-16 13:14 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        while i < size
В этом задании нужно реализовать итератор через рекурсию. Либо попробуй, либо отложи до лекции про ФП, делай следующее задание

2020-04-20 16:58 UTC, artempartos requested changes

2020-04-20 16:58 UTC, artempartos commented on test/exercise/fp2/solution.rb
> +        new_array = MyArray.new
Такая реализация будет работать. 
Но обычно когда ты объявляешь что то в начале, потом собираешь а потом возвращаешь - это явный признак того что надо использовать reduce
Воспользуйся уже готовой функцией my_reduce и реализуй через нее my_map и my_compact

2020-04-21 10:27 UTC, devality approved these changes

2020-04-21 10:53 UTC, merged